import { setTooltip } from 'obsidian';

/**
 * Fill a code-block container element with VitePress-style UI.
 *
 * `el` is the container element. We populate it in-place:
 *
 *   <div class="vp-markdown-body language-js">
 *     <button class="copy"></button>
 *     <span class="lang">js</span>
 *     <pre class="shiki ..."><code>…</code></pre>
 *     <div class="line-numbers-wrapper" aria-hidden="true">…</div>  (optional)
 *   </div>
 */

export function fillCodeBlock(
	el: HTMLElement,
	highlightedHtml: string,
	lang: string,
	lineNumbers: boolean,
	title: string = '',
	lineNumberStart: number = 1,
): void {
	// -- copy button (before the lang label so `.copy + .lang` works) --
	const copyBtn = activeDocument.createElement('button');
	copyBtn.classList.add('copy');
	// Single Obsidian-style tooltip only — no `title` attribute (that adds a
	// second, browser-native tooltip bubble on top of Obsidian's).
	setTooltip(copyBtn, '复制');
	el.appendChild(copyBtn);

	// -- language label --
	const langSpan = activeDocument.createElement('span');
	langSpan.classList.add('lang');
	langSpan.textContent = lang;
	el.appendChild(langSpan);

	// -- optional filename title bar (`[title]` on a standalone block) --
	if (title) {
		el.classList.add('vp-has-title');
		const titleBar = activeDocument.createElement('div');
		titleBar.classList.add('vp-code-title');
		titleBar.textContent = title;
		el.appendChild(titleBar);
	}

	// -- Shiki highlighted code (parsed from HTML string) --
	// The HTML is generated by our own Shiki pipeline, so it's trusted.
	// eslint-disable-next-line no-unsanitized/method
	const fragment = activeDocument
		.createRange()
		.createContextualFragment(highlightedHtml);
	el.appendChild(fragment);

	// Note: Shiki emits inline `style="background-color: …"` on <pre>/<code>,
	// but our CSS uses `background: transparent !important` on both, so the
	// inline values are already overridden — no manual style clearing needed.

	// -- line numbers --
	const pre = el.querySelector('pre');
	if (lineNumbers && pre) {
		const lineCount = pre.querySelectorAll('code .line').length;
		if (lineCount > 0) {
			const gutter = activeDocument.createElement('div');
			gutter.classList.add('line-numbers-wrapper');
			gutter.setAttribute('aria-hidden', 'true');
			for (let i = 0; i < lineCount; i++) {
				const span = activeDocument.createElement('span');
				span.classList.add('line-number');
				span.textContent = String(lineNumberStart + i);
				gutter.appendChild(span);
				gutter.appendChild(activeDocument.createElement('br'));
			}
			el.appendChild(gutter);
		}
	}

	// -- copy handler --
	copyBtn.addEventListener('click', () => {
		void handleCopyClick(el, copyBtn);
	});
}

async function handleCopyClick(el: HTMLElement, copyBtn: HTMLElement): Promise<void> {
	const codeEl = el.querySelector('code');
	if (!codeEl) return;

	const clone = codeEl.cloneNode(true) as HTMLElement;
	clone
		.querySelectorAll('.vp-copy-ignore, .diff.remove, .line-number')
		.forEach((n) => n.remove());

	let text = clone.textContent ?? '';
	text = text.replace(/\n{3,}/g, '\n\n').trim();

	try {
		await navigator.clipboard.writeText(text);
		copyBtn.classList.add('copied');
		setTooltip(copyBtn, '已复制');
		window.setTimeout(() => {
			copyBtn.classList.remove('copied');
			setTooltip(copyBtn, '复制');
		}, 2000);
	} catch {
		/* noop */
	}
}

// ---------------------------------------------------------------------------
// Single block wrapper
// ---------------------------------------------------------------------------

/**
 * Build a complete VitePress code-block element from already-highlighted HTML.
 */
export function renderCodeBlock(
	highlightedHtml: string,
	lang: string,
	lineNumbers: boolean,
	title?: string,
	lineNumberStart: number = 1,
): HTMLElement {
	const wrapper = activeDocument.createElement('div');
	wrapper.classList.add('vp-markdown-body', `language-${lang}`);
	if (lineNumbers) wrapper.classList.add('line-numbers-mode');
	fillCodeBlock(wrapper, highlightedHtml, lang, lineNumbers, title, lineNumberStart);
	return wrapper;
}

// ---------------------------------------------------------------------------
// Code group
// ---------------------------------------------------------------------------

export interface GroupItemRender {
	/** Shiki-highlighted `<pre><code>…</code></pre>` HTML. */
	html: string;
	lang: string;
	/** Tab label. */
	title: string;
	lineNumbers: boolean;
	lineNumberStart: number;
}

/**
 * Build a VitePress `::: code-group` element from a list of already-highlighted
 * blocks.  Identical markup is used in reading mode and the live-preview widget.
 *
 * Tabs are plain <button>s switched with JS (not the hidden-radio + label[for]
 * CSS trick), because in Obsidian the `position: fixed` radios steal focus / a
 * stray bubbled click can blank the view.
 */
export function renderCodeGroup(items: GroupItemRender[]): HTMLElement {
	const groupEl = activeDocument.createElement('div');
	groupEl.classList.add('vp-code-group');

	const tabs = activeDocument.createElement('div');
	tabs.classList.add('tabs');

	const blocks = activeDocument.createElement('div');
	blocks.classList.add('blocks');

	const tabEls: HTMLElement[] = [];
	const blockEls: HTMLElement[] = [];

	const activate = (idx: number): void => {
		tabEls.forEach((t, i) => t.classList.toggle('active', i === idx));
		blockEls.forEach((b, i) => b.classList.toggle('active', i === idx));
	};

	items.forEach((item, idx) => {
		const tab = activeDocument.createElement('button');
		tab.type = 'button';
		tab.classList.add('vp-tab');
		tab.setAttribute('data-title', item.title);
		tab.textContent = item.title;
		if (idx === 0) tab.classList.add('active');
		tab.addEventListener('click', (e) => {
			e.preventDefault();
			e.stopPropagation();
			activate(idx);
		});
		tabs.appendChild(tab);
		tabEls.push(tab);

		const blockWrapper = activeDocument.createElement('div');
		blockWrapper.classList.add('vp-block');
		if (idx === 0) blockWrapper.classList.add('active');
		// No title bar inside a group — the tab already shows the name.
		blockWrapper.appendChild(
			renderCodeBlock(item.html, item.lang, item.lineNumbers, '', item.lineNumberStart),
		);
		blocks.appendChild(blockWrapper);
		blockEls.push(blockWrapper);
	});

	groupEl.appendChild(tabs);
	groupEl.appendChild(blocks);

	return groupEl;
}
